name: Publish to PyPI
on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run build
      - uses: actions/checkout@v2
      - run: |
          python3 setup.py sdist bdist_wheel




