name: Publish to PyPI
on:
  push:
    branches:
      - deploy

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker build -t ltf .
      - name: Run tests
        run: docker run ltf
      - name: Deploy to PyPI
        env:
          PYPI_USER: "${{ secrets.PYPI_USER }}"
          PYPI_PSWD: "${{ secrets.PYPI_PSWD }}"
          PYPI_URL: "https://test.pypi.org/legacy/"
        run: docker run ltf pypi.sh