name: Publish to PyPI
on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build package
      - run: |
          python3 setup.py sdist bdist_wheel

  publsih:
    needs: build
    runs-on: ubuntu-latest
    name: Publish to PyPI
    steps:
      - name: Build
      - uses: actions/checkout@v2
      - run: |
         pip install twine
         twine upload -u ${{ secrets.PYPI_USER}} -p ${{ secrets.PYPI_PSWD }} --repository-url ${{ secrets.pypi_url }} dist/*

#https://test.pypi.org/legacy/
